### ISSUE TITLE
Correctly position calendar under input element

### ISSUE THREAD

**Issue by viveleroi** [720kb/angular-datepicker#137]
When the calendar is appended to an element other than the original input, it will no longer match the positioning unless they both happen to existing in the same container.

![](http://puu.sh/mvDZC/534ee62528.png)

It could be optional (especially when #136 is implemented) but the calendar should be positioned below the input. So the javascript will set it's width, top/left values.

However, it's important to keep in mind the edge of the viewport. One of the reasons we're considering this library for our app is because the `ui-bootstrap` datepicker fails to "shift" when the input is close to the edge of the viewport and the calendar would therefore extend off-screen.

**Comment by 45kb** [comment]
Hi @viveleroi  this is not possible, because, if you append the calendar somewhere else, it is impossible to set a CSS style for the calendar that could fit everyone's needs.

The only thing to do is to create your own CSS style for that.

Hope you'll understand.

**Comment by viveleroi** [comment]
It *is* possible through javascript and if you need a working example, look at `ui-bootstrap`. Can you account for 100% for all potential use-cases? *No* but that's true about anything. If you're going to decline to implement this, at least state that, rather than "it's not possible".

**Comment by 45kb** [comment]
@viveleroi  Hi, perhaps we misunderstood, almost anything is possible using javascript, the very difficult part is to know whether you and another person you need the same thing/feature.

Said that, to not generate entropy inside the module, it's better to leave this free from any coercion through js, so that anyone can adapt it to their own style and needs.

This is what i meant, i'm sorry if I expressed myself badly.

**Comment by viveleroi** [comment]
Thanks for your effort but we will not be using your product.

**Comment by 45kb** [comment]
@viveleroi  no problems :+1:
