### ISSUE TITLE
Loading date-min-limit="" dynamically does not update the calendar to required date.

### ISSUE THREAD

**Issue by jackdh** [720kb/angular-datepicker#169]
Say I was using 

> date-min-limit="{{minDate}}"

But minDate is set via a XHR request, it will correctly stop you entering a date smaller than the required min, but the actually picker will not auto shift to the first available date.

How can I get this to happen?

Thanks

**Comment by 45kb** [comment]
@jackdh Hi, there is no watcher on the date-min-limit attribute, due to too much listners we only left a watcher for `date-set`

So my suggestion is to retrieve the date limit from xhr and create the directive on the fly. Probably `ng-if` will help you, so that the directive is reinitiated everytime ng-if is true.
