### ISSUE TITLE
Dateformat dd-MM-yyyy fails

### ISSUE THREAD

**Issue by RobinBrackez** [720kb/angular-datepicker#254]
If you enter a European date format, like dd-MM-yyyy (first days, then month) the datepicker fails when the date can apply to both formats (like 05-04-2017 or 01-11-2017)/

The calender parses the date correctly in the textbox (dd-MM-yyyy), but it reads them as MM-dd-yyyy.

So if you select May 4th in the calender, the textbox will say "04/05/2017" (correct), but the calendar will show April 5th the next time you click it (incorrect).

Use this code in index.html to reproduce:

```
  <div class="col6 offset-left2">
    <div class="col3">
      <div class="datepicker"
      date-set-hidden="true"
      date-format="dd-MM-yyyy"
      date-set="26-11-2015"
      date-min-limit="01-01-2014"
      date-max-limit="01-01-2018"
      date-typer="true"
      button-prev='<i class="fa fa-arrow-circle-left"></i>'
      button-next='<i class="fa fa-arrow-circle-right"></i>'>
      <input ng-model="date2" type="text" class="angular-datepicker-input"/>
    </div>
  </div>
```

**Comment by FadiNouh1** [comment]
Did you find solution for this issue?

**Comment by RobinBrackez** [comment]
No. Didn't have the time to do so.

**Comment by PizzaPete** [comment]
What we did to work around this problem is having 2 input fields positioned over each other.
The EU date input field is shown and is underneath the US date input field. The US date input field is styled to be transparent.
Whenever a user clicks on the input field to select a date he thinks he selects the EU date input field, but in fact he clicks the US date input field. Then with a watch I watch for changes on the model that's on the datepicker and on a change I format the US date into the desired EU date format and put it on the model of the EU date input field.

It's not neat, but I didn't have time to dig into the issue. I hope this helps you guys further for the time being.

**Comment by samwx** [comment]
Anyone?

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/pull/257
