### ISSUE TITLE
Conflict with UI-Bootstrap Datepicker

### ISSUE THREAD

**Issue by tjsail33** [720kb/angular-datepicker#27]
The datepicker directive in angular-datepicker conflicts with the datepicker directive in ui-bootstrap. I'm not sure how to go about fixing this, but I would believe that many people using this module will also be utilizing pieces of ui-bootstrap as well.

**Comment by 45kb** [comment]
@tjsail33  are you sure ? I am asking you cause we already closed the bootstrap-ui compatibility issue here https://github.com/720kb/angular-datepicker/issues/12

**Comment by 45kb** [comment]
@tjsail33  I checked it it's quite simple, we need to restrict: 'EC' or even better restrict: 'AEC'  cause the boostrap-ui restric:'AE'

**Comment by 45kb** [comment]
@tjsail33  Ok i created and pushed a new branch (https://github.com/720kb/angular-datepicker/tree/ui-bootstrap-compatibility) for ui-bootstrap compatibility, it seems to work if you use class="datepicker" instead of <datepicker> , could be great if you try it before to merge it, just use the angular-datepicker.css and angular-datepicker.js files you find here (https://github.com/720kb/angular-datepicker/blob/ui-bootstrap-compatibility/src/css/angular-datepicker.css) and here (https://github.com/720kb/angular-datepicker/blob/ui-bootstrap-compatibility/src/js/angular-datepicker.js)

**Comment by tjsail33** [comment]
As I mentioned in my other comment, this fixes the issue for me on my localhost.

**Comment by 45kb** [comment]
@tjsail33  Glad that it works now, thank you a lot both for reporting and testing! :100:
