### ISSUE TITLE
The Icon Can't Display Well

### ISSUE THREAD

**Issue by LuckyKarin** [720kb/angular-datepicker#44]
I just opened this link (http://720kb.github.io/angular-datepicker/?utm_source=angular-js.in&utm_medium=website&utm_campaign=content-curation) with Chrome, but this icon marked red on the screenshot can't display well, I don't know why. And is it possible to fix it or make it customizable?
![qq 20150317180313](https://cloud.githubusercontent.com/assets/11519282/6685756/adf41efa-ccd7-11e4-897c-8a3016649e95.png)

**Comment by 45kb** [comment]
Hi @LuckyKarin  thank you for reporting :)

That icon is a simple html special character (&dtrif;) you can see it here https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L42

At the moment you can edit it, just fork and modify the code, you could add a new attribute for the directive, so that, using custom html or font icons code inside of it, everyone can customize it.

**Comment by LuckyKarin** [comment]
Thank you so much!

2015-03-17 19:20 GMT+08:00 Filippo <notifications@github.com>:

**Comment by 45kb** [comment]
@LuckyKarin  you're welcome, let me know if you try something for this ;)

**Comment by skrappyzz** [comment]
Hi, now this issue is still reproduce and I can't change this icon by attrs...
