### ISSUE TITLE
Datepicker type is typeof "string" after selecting a date.

### ISSUE THREAD

**Issue by Krummelz** [720kb/angular-datepicker#65]
I have the following html:

    <datepicker>
        <input type="text" ng-model="Person.DateOfBirth" />
    </datepicker>

After selecting the date, the DateOfBirth is a string, instead of a Date object. 
I checked `typeof Person.DateOfBirth` and it is indeed string

**Comment by 45kb** [comment]
@Krummelz  just tested out and it's true, the model is always type of string, in any case.

This is because we are triggering the input change event to update the model everytime a date is selected.

Actually we need more time to fix this but if you have some idea and would like to help feel free to fork and PR, i am sorry but i am sure this will get fixed in few time.

Thank you for reporting ! :+1:

**Comment by WillBrindle** [comment]
I needed this to return a date because I didn't want to have to keep parsing back to a date. For this I modified the code slightly. 

I added an extra binding ('dateModel': '=') which will now behave like ng-model. Whenever the date is changed that model will be updated. In the setInputValue I then as well as updating the input, I update $scope.model by using $scope.model in place of the local var modelDate.

The next issue after this was that the value would not display by default so I simply added in the link function:

    if (attr.dateFormat && $scope.model) {
			$timeout(function() {
				thisInput.val($filter('date')($scope.model, dateFormat));
				 $scope.month = $filter('date')($scope.model, 'MMMM');//December-November like
            	$scope.monthNumber = Number($filter('date')($scope.model, 'MM')); // 01-12 like
            	$scope.day = Number($filter('date')($scope.model, 'dd')); //01-31 like
            	$scope.year = Number($filter('date')($scope.model, 'yyyy'));//2014 like
				$scope.setDaysInMonth($scope.monthNumber, $scope.year);
			});
        }

This can be improved to have a default dateFormat instead of just not displaying. The other parts of that extract also ensure that the datepicker is all set to the model value.

Finally I added a change attribute ('change': '&') which I call in place of ensuring the change is called on the input.

This all probably has downsides to other uses of this but for my uses this works great. The changes are quite small and if anyone is interested I can fork this repo and put it up.
